# -*- coding: utf-8 -*-
"""Aula_mercado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLRNKe07EGHQEu8AQf4ENSxMa4GY1PuL
"""

nome='Júlia'
print(f'olá {nome}')

nome = 'Júlia'
idade = '22 anos'
cidade = 'campinas'

print(f'olá {nome},você tem {idade} e mora em {cidade}')

# o nosso desafio é mostrar os produtos de um mercado
# quero poder escolher os produtos, para ver infos
# quero poder adicionar novos produtos
# quero poder excluir um produto do mercado

#-----------------

# criar as variaáveis globais para o software
lista_produtos = ['Detergente Ype', 'Refrigerante Gengibirra', 'Arroz', 'Feijão', 'Água Mineral']
lista_preco = [2.50, 5, 7.25, 4, 3.45]

# para criarmos uma função
# para criarmos um apanhado de código, devemos
# armazenar eles dentro de um bloco e dar nome

# função 1 - ver produtos
def ver_produtos():
  print(f'Os produtos que temos são: {lista_produtos}')
  print(f'e seus preços são: {lista_preco}')

def adicionar_produtos():
  novo_produto = input('informe o nome do produto: ')
  novo_preco = float(input('informe o preço: '))
  lista_produtos.append(novo_produto)
  # /\ CHAMAMOS A LISTA - ATRIBUIMOS A FUNÇÃO APPEND (ADICIONA) -
  # COLOCAMOS O QUE VAI SER ADICIONADO
  lista_preco.append(novo_preco)

print('-----MENU DO MERCADO-----')
print('Escolha a opção')
print('1 - ver produtos')
print('2 - cadastrar novo produto')
opcao = int(input('informe a opção desejada'))

# O comando If serve para consicionar algo
# if condição operador (==) resposta:
if opcao == 1:
  # o que ele deve executar
  ver_produtos()
# o comando elif é a combinação do termos else (se nao) if (se)
elif opcao == 2:
  adicionar_produtos()
  ver_produtos()

# 1 criar uma lista com nome de 5 pets
# 2 criar uma função para exibir todos os pets
# 3 criar uma função para cadastrar um novo pet
# 4 criar um menu de opções para ver ou cadastrar pets

lista_nomes = ['Hayka', 'Toelho', 'Lala', 'Piquirito', 'Bolinha']
def ver_nomes():
  print(f'Os nomes de Pets são: {lista_nomes}')
def adicionar_nome():
  novo_nome = input('informe o novo nome: ')
  lista_nomes.append(novo_nome)

print('-----MENU DE OPCOES-----')
print('Escolha a opção')
print('1 - ver nomes')
print('2 - cadastrar novo nome')
opcao = int(input('informe a opção desejada'))
if opcao == 1:
  ver_nomes()
elif opcao == 2:
  adicionar_nome()
  ver_nomes()